---
mongodb_version: '8.3.4'
mongodb_major_version: '8.3'
mongodb_signing_key_version: '8.0'
mongodb_apt_arch: "{{ {'x86_64': 'amd64', 'aarch64': 'arm64'}.get(ansible_facts['architecture'], ansible_facts['architecture']) }}"
mongodb_bind_ip: '127.0.0.1'
mongodb_port: 27017
