---
- name: Deploy non-public CRM canary
  hosts: crm01
  become: true

  vars_files:
    - ../group_vars/all/main.yml
    - ../group_vars/all/vault.yml
    - ../group_vars/all/mongodb-secrets.yml

  roles:
    - crm
