---
crm_repository: 'https://github.com/Samir1919/realestate-crm.git'
crm_git_revision: '997f4b8cf0bc3902da9beae5a26988e1280ad7df'
crm_deploy_path: '/opt/realestate-crm'
crm_port: 3000
crm_database_host: '192.168.10.102'
crm_database_port: 27017
crm_database_name: 'crm_prod'
crm_database_user: 'crm_app'
